name: Windows RDP

on:
  workflow_dispatch:

jobs:
  rdp-1:
    runs-on: windows-latest
    timeout-minutes: 100000
    steps:
      - name: FULL SETUP
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
          $pass = ConvertTo-SecureString "Venom123!" -AsPlainText -Force
          New-LocalUser -Name "rdpuser" -Password $pass -PasswordNeverExpires -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member "rdpuser" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "rdpuser" -ErrorAction SilentlyContinue
          if (-not (Test-Path "ngrok.exe")) {
            Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
            Expand-Archive -Path "ngrok.zip" -DestinationPath "." -Force
          }
          Stop-Process -Name "ngrok" -ErrorAction SilentlyContinue
          .\ngrok.exe config add-authtoken 3ADvwGsqMHo6RDmYjXwwhRf5eTy_4PoMfkswQrNRH3eXPrQLZ
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
          Start-Sleep -Seconds 8
          $tunnels = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels"
          $clean = $tunnels.tunnels[0].public_url -replace 'tcp://',''
          $body = '{"content":"RDP: ' + $clean + '\nUser: rdpuser\nPass: Venom123!"}'
          Invoke-RestMethod -Uri "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc" -Method Post -Body $body -ContentType "application/json" -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 3000

      - name: FULL SETUP 2
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
          $pass = ConvertTo-SecureString "Venom123!" -AsPlainText -Force
          New-LocalUser -Name "rdpuser" -Password $pass -PasswordNeverExpires -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member "rdpuser" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "rdpuser" -ErrorAction SilentlyContinue
          if (-not (Test-Path "ngrok.exe")) {
            Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
            Expand-Archive -Path "ngrok.zip" -DestinationPath "." -Force
          }
          Stop-Process -Name "ngrok" -ErrorAction SilentlyContinue
          .\ngrok.exe config add-authtoken 3ADvwGsqMHo6RDmYjXwwhRf5eTy_4PoMfkswQrNRH3eXPrQLZ
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
          Start-Sleep -Seconds 8
          $tunnels = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels"
          $clean = $tunnels.tunnels[0].public_url -replace 'tcp://',''
          $body = '{"content":"RDP: ' + $clean + '\nUser: rdpuser\nPass: Venom123!"}'
          Invoke-RestMethod -Uri "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc" -Method Post -Body $body -ContentType "application/json" -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 3000

      - name: FULL SETUP 3
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
          $pass = ConvertTo-SecureString "Venom123!" -AsPlainText -Force
          New-LocalUser -Name "rdpuser" -Password $pass -PasswordNeverExpires -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member "rdpuser" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "rdpuser" -ErrorAction SilentlyContinue
          if (-not (Test-Path "ngrok.exe")) {
            Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
            Expand-Archive -Path "ngrok.zip" -DestinationPath "." -Force
          }
          Stop-Process -Name "ngrok" -ErrorAction SilentlyContinue
          .\ngrok.exe config add-authtoken 3ADvwGsqMHo6RDmYjXwwhRf5eTy_4PoMfkswQrNRH3eXPrQLZ
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
          Start-Sleep -Seconds 8
          $tunnels = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels"
          $clean = $tunnels.tunnels[0].public_url -replace 'tcp://',''
          $body = '{"content":"RDP: ' + $clean + '\nUser: rdpuser\nPass: Venom123!"}'
          Invoke-RestMethod -Uri "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc" -Method Post -Body $body -ContentType "application/json" -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 3000

      - name: FULL SETUP 4
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
          $pass = ConvertTo-SecureString "Venom123!" -AsPlainText -Force
          New-LocalUser -Name "rdpuser" -Password $pass -PasswordNeverExpires -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member "rdpuser" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "rdpuser" -ErrorAction SilentlyContinue
          if (-not (Test-Path "ngrok.exe")) {
            Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
            Expand-Archive -Path "ngrok.zip" -DestinationPath "." -Force
          }
          Stop-Process -Name "ngrok" -ErrorAction SilentlyContinue
          .\ngrok.exe config add-authtoken 3ADvwGsqMHo6RDmYjXwwhRf5eTy_4PoMfkswQrNRH3eXPrQLZ
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
          Start-Sleep -Seconds 8
          $tunnels = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels"
          $clean = $tunnels.tunnels[0].public_url -replace 'tcp://',''
          $body = '{"content":"RDP: ' + $clean + '\nUser: rdpuser\nPass: Venom123!"}'
          Invoke-RestMethod -Uri "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc" -Method Post -Body $body -ContentType "application/json" -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 3000

      - name: FULL SETUP 5
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
          $pass = ConvertTo-SecureString "Venom123!" -AsPlainText -Force
          New-LocalUser -Name "rdpuser" -Password $pass -PasswordNeverExpires -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member "rdpuser" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "rdpuser" -ErrorAction SilentlyContinue
          if (-not (Test-Path "ngrok.exe")) {
            Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
            Expand-Archive -Path "ngrok.zip" -DestinationPath "." -Force
          }
          Stop-Process -Name "ngrok" -ErrorAction SilentlyContinue
          .\ngrok.exe config add-authtoken 3ADvwGsqMHo6RDmYjXwwhRf5eTy_4PoMfkswQrNRH3eXPrQLZ
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
          Start-Sleep -Seconds 8
          $tunnels = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels"
          $clean = $tunnels.tunnels[0].public_url -replace 'tcp://',''
          $body = '{"content":"RDP: ' + $clean + '\nUser: rdpuser\nPass: Venom123!"}'
          Invoke-RestMethod -Uri "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc" -Method Post -Body $body -ContentType "application/json" -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 3000

      - name: FULL SETUP 6
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
          $pass = ConvertTo-SecureString "Venom123!" -AsPlainText -Force
          New-LocalUser -Name "rdpuser" -Password $pass -PasswordNeverExpires -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member "rdpuser" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "rdpuser" -ErrorAction SilentlyContinue
          if (-not (Test-Path "ngrok.exe")) {
            Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
            Expand-Archive -Path "ngrok.zip" -DestinationPath "." -Force
          }
          Stop-Process -Name "ngrok" -ErrorAction SilentlyContinue
          .\ngrok.exe config add-authtoken 3ADvwGsqMHo6RDmYjXwwhRf5eTy_4PoMfkswQrNRH3eXPrQLZ
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
          Start-Sleep -Seconds 8
          $tunnels = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels"
          $clean = $tunnels.tunnels[0].public_url -replace 'tcp://',''
          $body = '{"content":"RDP: ' + $clean + '\nUser: rdpuser\nPass: Venom123!"}'
          Invoke-RestMethod -Uri "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc" -Method Post -Body $body -ContentType "application/json" -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 3000

      - name: FULL SETUP 7
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
          $pass = ConvertTo-SecureString "Venom123!" -AsPlainText -Force
          New-LocalUser -Name "rdpuser" -Password $pass -PasswordNeverExpires -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member "rdpuser" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "rdpuser" -ErrorAction SilentlyContinue
          if (-not (Test-Path "ngrok.exe")) {
            Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
            Expand-Archive -Path "ngrok.zip" -DestinationPath "." -Force
          }
          Stop-Process -Name "ngrok" -ErrorAction SilentlyContinue
          .\ngrok.exe config add-authtoken 3ADvwGsqMHo6RDmYjXwwhRf5eTy_4PoMfkswQrNRH3eXPrQLZ
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
          Start-Sleep -Seconds 8
          $tunnels = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels"
          $clean = $tunnels.tunnels[0].public_url -replace 'tcp://',''
          $body = '{"content":"RDP: ' + $clean + '\nUser: rdpuser\nPass: Venom123!"}'
          Invoke-RestMethod -Uri "https://discord.com/api/webhooks/1461013177658769602/mjg15yU9egXIhpHMvomG2Brb5ASM8WJ8ca0CE-Foi_HHpTXox_LfTsYOLH-bv1xgzSKc" -Method Post -Body $body -ContentType "application/json" -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 3000
